### ISSUE TITLE
Error compiling repository 

### ISSUE THREAD

**Issue by srinivasmangipudi** [nigeon/CryptoZombies#3]
I am getting this error when I try to compile a freshly cloned repository:

`Error: Truffle is currently using solc 0.5.16, but one or more of your contracts specify "pragma solidity ^0.4.18".
`
I changed the versions in the files but it still throws errors for the zepplin-safemath.sol etc imported contracts.

Before this there was also a problem with running npm install on the repo.
```
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by nigeon** [comment]
Well, repo is 2 years old now..... this can be thousands of different things :S
